
name: Container Build

inputs:
  ecr-repository-uri:
    required: true
    description: ECRリポジトリのURI
  dockerfile-path:
    required: true
    description: Dockerfileのパス
  platforms:
    required: false
    description: ビルドするプラットフォーム
    default: linux/arm64

outputs:
  container-image:
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: composite
  steps:
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Generate Docker Image Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.ecr-repository-uri }}
        tags: type=sha

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        push: true
        file: ${{ inputs.dockerfile-path }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
